site: Form + Structure

url: https://formandstructure.co
baseurl:

exclude:
  - node_modules
  - package.json
  - package-lock.json
  - install-modules.mjs

keep_files:
  - web_modules

collections:
  pages:
    output: true
    permalink: /:name
  projects:
    output: true
    permalink: /project/:slug

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 6
paginate_path: "/blog/page:num/"
